### ISSUE TITLE
no click get url，how?

### ISSUE THREAD

**Issue by 2qq2qq** [CliffCloud/Leaflet.LocationShare#3]
thank you

**Comment by atstp** [comment]
what do you mean by "Direct display"?  do you want to navigate to the url?

**Comment by atstp** [comment]
re-defining the global `copyPrompt` might help (see below), but I'm not sure exactly what you want.

```
function copyPrompt() {
    window.location.href = (
        '' + location.origin + location.pathname + '?' + 
        'lat' + '=' + LS.Send.lat + '&' +
        'lng' + '=' + LS.Send.lng + '&' +
        'M' + '=' +  LS.Send.Message
    );
};
```

**Comment by 2qq2qq** [comment]
I want to position of my markers with getLatLng.
But if i draggable a marker,
position no update
my code:


`map.on('contextmenu',addPoint);
function addPoint(e)
{
var marker = L.marker([e.latlng.lat, e.latlng.lng],{draggable:true}).addTo(map).bindPopup(e.latlng.toString()).openPopup();
}`
