### ISSUE TITLE
marker in the center of the map

### ISSUE THREAD

**Issue by lem7974** [CliffCloud/Leaflet.LocationShare#4]
good afternoon. how to make a marker in the center of the map and zoomed?
https://cliffcloud.github.io/Leaflet.LocationShare/?lat=49.03786794532644&lng=10.986328125&M=undefined

**Comment by Ferretdog** [comment]
Try this - put it in the bottom of your HTML before the </script>

`map.setView([LS.Receive.lat , LS.Receive.lng], 13); 
`

The 13 is the zoom, this code works fine in the page even when it is not receiving a shared location as it just ignores it

**Comment by atstp** [comment]
Ferretdog's suggestion looks great :+1:
